spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  config:
    import: 
      - optional:application-oauth.yml
      - optional:file:.env[.properties]

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.pawject.domain

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  issuer: pawject
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 900       # 15분
  refresh-token-exp-seconds: 1209600  # 14일
  header: Authorization
  prefix: Bearer

file:
  upload-path: /home/ubuntu/app/back/build/libs/uploads
  upload-dir: /home/ubuntu/app/back/build/libs/uploads


app:
  oauth2:
    redirect-url: http://3.38.218.56/oauth2/callback
    #redirect-url: http://localhost:3000/oauth2/callback

## 개인 api 오류 방지용 - 빈값 넣어주세요 (공용)
openai:
  api:
    key:
      hj: ""

naver:
  ocr:
    key: ""
    url: ""

